### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [jr-consulting/kodilla-js8.11-repository#1]
- [ ] popraw proszę wcięcia w js, ponieważ teraz jest to nieczytelne - w pierwszej chwili myslalem, ze caly kod jest w pierwszej funkcji
- [ ] zamiast `'<li>item' + ' ' + ...` mozesz napisac `'<li>item ' + ...`

**Comment by jr-consulting** [comment]
ad 1. done
ad 2. done

**Comment by zdolny** [comment]
git :)
